### ISSUE TITLE
Empty rule

### ISSUE THREAD

**Issue by vdechenaux** [K-Phoen/rulerz#20]
Hi!

What do you think about the support of empty rule?
It should return all the data when we use the `filter` method and always return `true` with `satisfies`.
Currently, if we use a blank rule, it throw a `Hoa\Compiler\Exception\UnexpectedToken` with this message:

> Unexpected token "EOF" (EOF) at line 1 and column 1

Thanks!

**Comment by K-Phoen** [comment]
Hi!

Allowing empty rules and giving them a special meaning ‒ _always true_ ‒ feels a bit weird.
The whole point of this library is to express business rules, so if you don't have anything to express I don't think it make sense for RulerZ to interpret it as _anything_. On the contrary, if I was to implement this empty rule thing, I think that I would give them the meaning of _always false_.

What do you think?

**Comment by mnapoli** [comment]
Mhh that's an interesting POV. The way I see it if you use rules to "search" or restrict a set of items, an empty query returns all the results (because there are no constraints to satisfy, hence all items are valid). Just like an empty SQL `WHERE` clause.

In our case we currently have custom logic to cover that (because rules can be empty), but we were thinking that it might make sense to move that behavior back in here. If not, that's fine, after all it works for us today.

**Comment by K-Phoen** [comment]
Almost two month after, I still think than an empty rule is invalid. I like to see my rules more as specifications than just where clauses.

For the reasons I stated before, I close this issue :)
