### ISSUE TITLE
DoctrineQueryBuilderVisitor compile issue

### ISSUE THREAD

**Issue by kandelyabre** [K-Phoen/rulerz#36]
\RulerZ\Compiler\Target\Sql\DoctrineQueryBuilderVisitor::$detectedJoins must be reseted after compilation, otherwise one rule will use $detectedJoins data of previous rule

**Comment by kandelyabre** [comment]
possible solution https://github.com/K-Phoen/rulerz/pull/37

**Comment by K-Phoen** [comment]
Thanks for opening this issue!

This issue should be fixed in [this branch](https://github.com/K-Phoen/rulerz/tree/doctrine-compile-time-metadata).

In addition to a fix for this issue, this branch refactors and improves a lot of stuff. That's why I won't merge #37 and work instead on finishing the new branch.

**Comment by kandelyabre** [comment]
so you working on major version, but this is minor fix and all who has dependencies on 0.18 may faced with this bug :-\

**Comment by K-Phoen** [comment]
It's not a major version as this library is still in 0.x ;)
Furthermore, this branch is almost ready and could be merged very soon.

If it's not the case in a couple of days, I'll merge a patch similar to your's as a temporary fix.

**Comment by kandelyabre** [comment]
thanks, will wait for new version or fix :)

**Comment by K-Phoen** [comment]
I tagged [0.19.1](https://github.com/K-Phoen/rulerz/releases/tag/0.19.1) with a fix similar to yours :)

**Comment by kandelyabre** [comment]
Great! Thanks :)
